/* Public work summaries and images. Original CV and presentation PDFs are linked from Drive, not hosted here. */
window.AMR_DATA = {
  services: [
    { number: '01', icon: 'chart', title: 'Financial modeling & valuation', text: 'Understand the drivers behind a business with structured financial models and clearly documented assumptions.', deliverable: 'Three-statement models · DCF analysis · Financial forecasts', tags: ['Excel', 'Financial Analysis', 'DCF'] },
    { number: '02', icon: 'database', title: 'Business data & dashboards', text: 'Turn scattered data into a consistent view of performance that your team can explore and explain.', deliverable: 'Data cleaning · KPI reporting · Interactive dashboards', tags: ['Power BI', 'SQL', 'Python'] },
    { number: '03', icon: 'document', title: 'Presentations', text: 'Connect company and industry research to a financial story that people can follow.', deliverable: 'Company research · Financial presentations · Business storytelling', tags: ['PowerPoint', 'Excel'] }
  ],
  experience: [
    { period: 'JUN – DEC 2025', title: 'Data Analyst Intern', company: 'Digital Egypt Pioneers Initiative', description: 'Cleaned and organized datasets, explored trends using Excel, SQL, and Python, and built Power BI dashboards to communicate business insights.' },
    { period: 'SEP 2025 – PRESENT', title: 'Vice President', company: 'Rally · Alexandria University', description: 'Leading an executive board and supporting student entrepreneurship through collaboration with institutions and startup communities.' },
    { period: '2024 & 2025', title: 'Speakers Relations Team', company: 'Alexandria Techne Summit', description: 'Coordinated high-profile guests and facilitated meetings between speakers, sponsors, and partners.' }
  ],
  projects: [
    { id: 'arabian', number: '01', title: 'Arabian Cement Company', image: 'images/arabian_cement.png', presentation: 'https://drive.google.com/file/d/1gydvKfzO4W0UHA6UPcweJQt3ZJD78YSn/view?usp=sharing', category: 'INDUSTRIALS / EQUITY RESEARCH', context: 'A team research study connecting the cement industry, operational performance, and company valuation.', approach: 'Historical financial review, five-year forecasts, and discounted cash flow valuation.', outcome: 'A complete presentation linking business drivers to the valuation assumptions.', tags: ['Company Research', 'Forecasting', 'DCF Valuation'], credit: 'Collaborative project · Amr Tamer & team', team: [{ name: 'Jomana Negm', url: 'https://www.linkedin.com/in/jomana-negm?utm_source=share_via&utm_content=profile&utm_medium=member_ios' }, { name: 'Youssef Essam', url: 'https://www.linkedin.com/in/youssefessamel-din022' }], thanks: 'Special thanks to the rest of the team.' },
    { id: 'elsewedy', number: '02', title: 'Elsewedy Electric', image: 'images/Elsewedy-cover.png', presentation: 'https://drive.google.com/file/d/1_tynoRYgP1OFUTlBFHuLwk6K_i3UU0cj/view?usp=sharing', category: 'ENERGY & INFRASTRUCTURE', context: 'A company study of energy and infrastructure operations and long-term growth drivers.', approach: 'Segment analysis, five-year projections, and DCF valuation with supporting financial schedules.', outcome: 'A research presentation connecting operational drivers to an explicit financial model.', tags: ['Financial Modeling', 'Industry Analysis'], credit: 'Collaborative project · Amr Tamer & Omar Samir', team: [{ name: 'Omar Samir', url: 'https://www.linkedin.com/in/omar-ahmed-samir-b80a68375' }] },
    { id: 'telecom', number: '03', title: 'Telecom Egypt / WE', image: 'images/WE.png', presentation: 'https://drive.google.com/file/d/1iAfQ-l37-m_OvgjgrsqSe03BPD8aKlNW/view?usp=sharing', category: 'TELECOMMUNICATIONS', context: 'A joint presentation exploring Telecom Egypt within the Egyptian telecom sector.', approach: 'Industry and business analysis, financial projections, and cash flow valuation.', outcome: 'A structured presentation bringing market context and valuation calculations together.', tags: ['Equity Research', 'Financial Analysis'], credit: 'Collaborative project · Amr Tamer & Omar Samir', team: [{ name: 'Omar Samir', url: 'https://www.linkedin.com/in/omar-ahmed-samir-b80a68375' }] }
  ],
  certificates: [
    { id: 'modeling', image: 'images/1.png', width: 1295, height: 905, title: 'Building a 3-Statement Model in Excel', issuer: '365 Financial Analyst', date: 'MARCH 2026', description: 'Connecting the income statement, balance sheet, and cash flow statement in one financial model. A stronger foundation for understanding how a business works.', tags: ['Excel', 'Financial Modeling'] },
    { id: 'dcf', image: 'images/2.png', width: 1329, height: 907, title: 'Discounted Cash Flow Valuation', issuer: '365 Financial Analyst', date: 'MARCH 2026', description: 'Developing a structured approach to cash flow forecasts, discount rates, and business valuation—while keeping the assumptions visible.', tags: ['DCF Valuation', 'Corporate Finance'] },
    { id: 'depi', image: 'images/DEPI.png', width: 1123, height: 793, title: 'Data Analyst Specialist', issuer: 'Digital Egypt Pioneers Initiative', date: 'JUN – DEC 2025', subtitle: 'Turning data into a business perspective.', description: 'Practical training in collecting, cleaning, and analyzing data, with dashboards that turn technical findings into useful business insights.', tags: ['Power BI', 'SQL', 'Python'] },
    { id: 'mckinsey', image: 'images/McKinsey.png', width: 1055, height: 812, title: 'McKinsey.org Forward', issuer: 'McKinsey.org', date: 'JULY 2025', subtitle: 'Professional skills for a changing world.', description: 'Completed the Forward online learning program, developing structured problem-solving, effective communication, adaptability, and digital skills.', tags: ['Problem Solving', 'Communication', 'Adaptability'] },
    { id: 'dreem', image: 'images/dreem_cert.jpeg', width: 1284, height: 893, title: '2026 Summer Training Program', issuer: 'Dreem', date: '2026', subtitle: 'A practical summer learning milestone.', description: 'Certificate of completion for Dreem’s 2026 Summer Training Program, recognizing active participation and commitment throughout the program.', tags: ['Summer Training', 'Professional Development'] }
  ]
};
